// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package rdbms

import (
	"time"
)

type StockMetum struct {
	StockID     string
	StockCode   string
	FetchOrigin string
	StockName   string
	CreatedAt   time.Time
}

type StoreLog struct {
	StockID  string
	StoredAt time.Time
	Status   string
}
