// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package rdbms

import (
	"time"
)

type AccessLog struct {
	ConnectedAt time.Time
}

type Stock struct {
	StockID     string
	FetchOrigin string
}
